config/routes.rb
Rails.application.routes.draw do

  get "/books" => "books#index", as: 'books'
  get "/books/new" => "books#new", as: 'new_book'
  get "/books/:id" => "books#show", as: 'book'
  post "/books" => "books#create"
  get "/books/:id/edit" => "books#edit", as: 'edit_book'
  patch "/books/:id" => "books#update"
  delete "/books/:id" => "books#destroy"

  get "/users" => "users#index", as: 'users'
  get "/users/new" => "users#new", as: 'new_user'
  get "/users/:id" => "users#show", as: 'user'
  post "/users" => "users#create"
  get "/users/:id/edit" => "users#edit", as: 'edit_user'
  patch "/users/:id" => "users#update"
  delete "/users/:id" => "users#destroy"

  resources :books, :users do
     get 'page/:page', :action => :index, :on => :collection
  end

namespace :users do
  root to: "#index"
end

root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [ :show, :edit, :update, :destroy ]

  def index

    @available_at = Time.now
    @books = Book.order(:title).page(params[:page])

  end

  def show



  end

  def new
    @book = Book.new
  end



 def create
  @book = Book.new(book_params)
  if @book.save

    redirect_to @book, notice: "#{@book.title} was created!"

  else
    render :new
  end
end




  def edit

  end

  def update
  if @book.update(book_params)

    redirect_to @book, notice: "#{@book.title} was updated!"

  else
    render :edit
  end
end



  def destroy

    @book.destroy
    redirect_to books_url
  end



  private

  def book_params
    params.require(:book).permit(:title, :author_id, :pages, :isbn, :abstract, :image_cover_url)
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [ :show, :edit, :update, :destroy ]

  def index

    @available_at = Time.now
    @users = User.order(:name).page(params[:page])

  end

  def show



  end

  def new
    @user = User.new
  end



 def create
  @user = User.new(user_params)
  if @user.save

    redirect_to @user, notice: "#{@user.name} was created!"

  else
    render :new
  end
end




  def edit

  end

  def update
  if @user.update(user_params)

    redirect_to @user, notice: "#{@user.name} was updated!"

  else
    render :edit
  end
end



  def destroy

    @user.destroy
    redirect_to users_url
  end



  private

  def user_params
    params.require(:user).permit(:name, :user_id, :password_digest, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
  end
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <%= render 'shared/validation_errors', object: @book %>
  <%= f.label :title %> <%= f.text_field :title, autofocus: true %><br />

  <%= f.label :author_id %> <%= f.text_field :author_id %><br />
  <%= f.label :pages %> <%= f.text_field :pages %><br />
  <%= f.label :isbn %> <%= f.text_field :isbn %><br />
  <%= f.label :abstract %> <%= f.text_area :abstract %><br />
  <%= f.label :genre %> <%= f.text_field :genre %><br />
  <%= f.label :published_on %> <%= f.text_field :published_on %><br />
  <%= f.label :image_cover_url %> <%=f.text_field :image_cover_url %>
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', books_path %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Editing <%= @book.title %></h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1>All Books</h1>
<p>Available as <%= formatted_time(@available_at) %></p>
<%= page_entries_info @books %>
<ol>

<% @books.each do |book| %>
  <li><%= link_to (image_tag(book.image_cover_url)) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size = 5><%= link_to(book.title, book) %> by <%= book.author_id %></li>
  <p>&nbsp;</p>
<% end %>
</ol>
<%= paginate @books %>

app/views/books/new.html.erb
<h1>Create a New Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<% content_for :title, @book.title %>


<article class="book">
  <header>
    <h2><strong><%= @book.title %></strong></h2>
  </header>
  <p><%= image_tag @book.image_cover_url %> <%= @book.abstract %></p>
  <p style="font-size:160%;"><strong>Details</strong></p>
  <p><label>Book ID number:</label> <%= @book.id %></p>
  <p><label>Author ID:</label> <%= @book.author_id %></p>
  <p><label>ISBN:</label> <%= @book.isbn %></p>

  <p><label>Pages:</label> <%= @book.pages %></p>
  <p><label>Genre:</label> <%= @book.genre %></p>
  <p><label>Published on:</label> <%= @book.published_on %></p>


</article><%= link_to 'All Books', books_path %>
| <%= link_to 'Edit', edit_book_path(@book) %>

<%= button_to 'Delete', @book,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Library', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Things to do...</h3>
    </div>
    <div class="panel-body">
      <p>
        <%= link_to 'All Books', books_path %>
      </p>
      <p>
        <%= link_to 'Create Book', new_book_path %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/validation_errors', object: @user %>
  <%= f.label :name %> <%= f.text_field :name, autofocus: true %><br />
  <%= f.label :user_id %> <%= f.text_field :user_id %><br />
  <%= f.label :password_digest %> <%= f.text_field :password_digest %><br />
  <%= f.label :admin %> <%= f.text_field :admin %><br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', books_path %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Editing <%= @user.name %></h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Users</h1>
<p>Available as of <%= formatted_time(@available_at) %></p>
<%= page_entries_info @users %>
<ol>

<% @users.each do |user| %>
  <li><%= link_to(user.name, user) %></li>
  <p>&nbsp;</p>
<% end %>
</ol>
<%= paginate @users %>

app/views/users/new.html.erb
<h1>Create a New User</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :name, @user.name %>


<article class="name">
  <header>
    <h2><%= @user.name %></h2>
  </header>
  <p><label>User ID number:</label> <%= @user.id %></p>
  <p><label>Admin:</label> <%= @user.admin %></p>

</article><%= link_to 'All Users', users_path %>
| <%= link_to 'Edit', edit_user_path(@user) %>

<%= button_to 'Delete', @user,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>